import 'dictation_result.dart';

/// Minimal study record generated by dictation submissions.
class StudyRecord {
  const StudyRecord({
    required this.itemId,
    required this.studyPhase,
    required this.answer,
    required this.result,
    required this.createdAt,
    this.skipped = false,
  });

  final String itemId;

  /// The phase is fixed to `dictation` for records emitted by DictationPage.
  final String studyPhase;
  final String answer;
  final DictationResultStatus result;
  final DateTime createdAt;
  final bool skipped;

  Map<String, Object?> toJson() {
    return <String, Object?>{
      'item_id': itemId,
      'study_phase': studyPhase,
      'answer': answer,
      'result': result.name,
      'created_at': createdAt.toIso8601String(),
      'skipped': skipped,
    };
  }
}
